# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f22cfd1c4a6262bf971be1a61aa6165d2866e974559dd8fe965eeeb7c478689d7da33b75c635d6538093873c434af6539250601ef613ce17bf343080fd53a57b

test:
  secret_key_base: 7e2d04d64991d355c775740c2d29c0439005e2e5edd3e2aa3f15e9a3a6b501a65624fb5a40a7c3ba7c5efe418f39c5d039968e148694a2dd003dcf33b13f2926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
